server:
  port: 8081

spring:
  profiles: test

  datasource:
    username: root
    password: admin123
    url: jdbc:mysql://47.93.185.66:3307/videoManagementSystem?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    dbcp2:
      min-idle: 10
      initial-size: 10
      max-wait-millis: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      remove-abandoned-on-borrow: true
      remove-abandoned-on-maintenance: true
      connection-init-sqls: set names utf8mb4

#redis配置信息
redis:
  database: 0
  host:
  password:
  port: 6380
  timeout: 5000
  pool:
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.videomanagementsystem.domain

kafka:
  bootstrap-servers: 47.93.185.66:5672
  topic: wujinfan
  producer:
    retries: 0
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-deserializer: org.apache.kafka.common.serialization.StringSerializer
    batch-size: 65536
    buffer-memory: 524288
  consumer:
    enable:
      auto:
        commit: true #是否自动提交
    session:
      timeout: 20000 #链接超时时间
    auto:
      commit:
        interval: 100
      offset:
        reset: earliest
    group:
      id: consumer-group-id  #消费组id
    concurrency: 10   #设置消费线程数

pagehelper:
  helperDialect: mysql
  reasonable: true                #开启优化，如果开启优化，在分页页码结果没有数据的时候,会显示有数据的页码数据
  supportMethodsArguments: true   #是否支持接口参数来传递分页参数，默认false
  pageSizeZero: false             #pageSize=0 返回所有
  params: count=countSql

logging:
    level:
      com:
        example:
          videomanagementsystem:
            mapper : debug
